global:
  isLocalEnv: false
  containerRegistry:
    path: moss-harbor.qiyi.domain/kyma
  istio:
    gateway:
      name: kyma-gateway
  acceptance_tests:
    dir:
    version: 2122254e
  disableLegacyConnectivity: "false"
test:
  acceptance:
    service_catalog:
      enabled: true
