global:
  isLocalEnv: false
  containerRegistry:
    path: moss-harbor.qiyi.domain/kyma
  istio_webhook:
    dir: develop/
    version: 84219cbc
  istio_kyma_patch:
    dir:
    version: d022112f
  required_istio_version: 1.4.7-distroless
