# Default values for knative-provisioner-natss.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  isLocalEnv: false
  natsStreaming:
    url: "nats-streaming.natss:4222"

knative-provisioner-natss:
  controller:
    image:
      pullPolicy: IfNotPresent
      gcr:
        io/knative-releases/knative:
      location: moss-harbor.qiyi.domain/knative/channel_controller:0.12.0
  dispatcher:
    image:
      pullPolicy: IfNotPresent
      location: moss-harbor.qiyi.domain/knative/channel_dispatcher:0.12.0
