webhook:
  replicaCount: 1
  image:
    repository: moss-harbor.qiyi.domain/kyma/podpreset-webhook
    tag: 6fe6c8dc
    pullPolicy: IfNotPresent
  verbosity: 6
  securityContext:
    runAsUser: 2000

controller:
  enabled: false
  image:
    repository: moss-harbor.qiyi.domain/kyma/podpreset-controller
    tag: 6fe6c8dc
    pullPolicy: IfNotPresent
