service:
  port: 8000
  name: iam-kubeconfig-service

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 32Mi
global:
  isLocalEnv: false
  istio:
    gateway:
      name: kyma-gateway
  containerRegistry:
    path: moss-harbor.qiyi.domain/kyma
  iam_kubeconfig_service:
    dir:
    version: b4ca26d4
