global:
  containerRegistry:
    path: moss-harbor.qiyi.domain/kyma
  istio:
    gateway:
      name: kyma-gateway
  service_binding_usage_controller:
    dir:
    version: 78ca96ab
  ingress:
    domainName: "TBD"
