---
kyma:
  namespaces2Label:
    - istio-system
    - kube-system
  labelJob:
    image: moss-harbor.qiyi.domain/kyma/alpine-kubectl
    tag: "v20200310-5f52f407"

istio:
  installer:
    image: moss-harbor.qiyi.domain/kyma/istio-installer
    tag: "ce7e3510"