---
kyma:
  namespaces2Label:
    - istio-system
    - kube-system
  labelJob:
    image: moss-harbor.qiyi.domain/kyma/alpine-kubectl
    tag: "v20200617-32c1f3ff"

istio:
  installer:
    image: moss-harbor.qiyi.domain/kyma/istio-installer
    tag: d022112f
