deployment:
  image:
    pullPolicy: IfNotPresent
  resources: {}
  strategy: {}
images:
  containerRegistry:
    path: moss-harbor.qiyi.domain/kyma
  ui:
    dir: null
    version: befe2f31
mf:
  host: compass-mf
service:
  externalPort: 81
  internalPort: 81
  mfExternalPort: 8888
  mfInternalPort: 8888
statusPort: 6082
ui:
  host: compass
